name: '${name}'
main: '${group}.${name}'

authors:
  - ryderbelserion
  - BadBones69
  - Felux
  - TDL
  - siberanka

version: '${version}'
description: '${description}'
api-version: '1.21'
website: '${website}'

softdepend: [HeadDatabase]

folia-supported: true

commands:
  blockparticle:
    description: Adds particles to blocks!
    aliases: [blockparticles, bp, bparticle, bparticles]

permissions:
  bparticles.admin:
    default: op
    description: Allows access to /blockparticles